name: "Continuous Integration"

on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    tests:
        name: "Tests"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "lowest"
                    - "highest"
                    - "locked"
                php-version:
                    - "7.4"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                operating-system:
                    - "ubuntu-latest"
                    - "windows-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.26.0"
                with:
                    coverage: "pcov"
                    php-version: "${{ matrix.php-version }}"
                    ini-values: memory_limit=-1

            -   name: "Install dependencies"
                uses: "ramsey/composer-install@2.2.0"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Tests"
                run: "composer test"
